# Generated by Django 3.1 on 2020-08-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='site_name',
            field=models.CharField(choices=[('bhp_hq', 'BHP HQ'), ('mmabana', 'Mmabana'), ('tsepamo', 'Tsepamo'), ('PEPFAR', 'PEPFAR'), ('hr_finance', 'HR/Finance'), ('hptn', 'HPTN'), ('ambition', 'Ambition'), ('ctu', 'CTU')], default=None, max_length=20, verbose_name='Site name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='site_name',
            field=models.CharField(choices=[('bhp_hq', 'BHP HQ'), ('mmabana', 'Mmabana'), ('tsepamo', 'Tsepamo'), ('PEPFAR', 'PEPFAR'), ('hr_finance', 'HR/Finance'), ('hptn', 'HPTN'), ('ambition', 'Ambition'), ('ctu', 'CTU')], default=None, max_length=20, verbose_name='Site name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temperature',
            name='site_name',
            field=models.CharField(choices=[('bhp_hq', 'BHP HQ'), ('mmabana', 'Mmabana'), ('tsepamo', 'Tsepamo'), ('PEPFAR', 'PEPFAR'), ('hr_finance', 'HR/Finance'), ('hptn', 'HPTN'), ('ambition', 'Ambition'), ('ctu', 'CTU')], max_length=20, verbose_name='Site name'),
        ),
    ]
